config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  draw :madmin
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
authenticate :user, lambda { |u| u.admin? } do
  mount Sidekiq::Web => '/sidekiq'

  namespace :madmin do
    resources :impersonates do
      post :impersonate, on: :member
      post :stop_impersonating, on: :collection
    end
  end
end

  # resources :notifications, only: [:index]
  # resources :announcements, only: [:index]
  resources :posts, except: [:new]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  devise_scope :user do
    get '/users/:id/profile' => 'users#profile', :as => 'user_profile'
  end
  devise_scope :announcements do
    get '/announcements/:id' => 'announcements#show', :as => 'announcements_post'
  end
  root to: 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/announcement.rb
class Announcement < ApplicationRecord
  TYPES = %w{ new fix update }

  after_initialize :set_defaults

  validates :announcement_type, :description, :name, :published_at, presence: true
  validates :announcement_type, inclusion: { in: TYPES }

  def set_defaults
    self.published_at      ||= Time.zone.now
    self.announcement_type ||= TYPES.first
  end
end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
  before_action :mark_as_read, if: :user_signed_in?

  def index
    @announcements = Announcement.order(published_at: :desc)
  end

  def show
    @announcements = Announcement.find(params[:id])
  end

  private

    def mark_as_read
      current_user.update(announcements_last_read_at: Time.zone.now)
    end
end

app/controllers/madmin/announcements_controller.rb
module Madmin
  class AnnouncementsController < Madmin::ResourceController
  end
end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
  def unread_announcements(user)
    last_announcement = Announcement.order(published_at: :desc).first
    return if last_announcement.nil?

    # Highlight announcements for anyone not logged in, cuz tempting
    if user.nil? || user.announcements_last_read_at.nil? || user.announcements_last_read_at < last_announcement.published_at
      "unread-announcements"
    end
  end

  def announcement_class(type)
    {
      "new" => "text-success",
      "update" => "text-warning",
      "fix" => "text-danger",
    }.fetch(type, "text-success")
  end
end

app/views/announcements/index.html.erb
<h1>What's New</h1>

<div class="card">
  <div class="card-body">
    <% @announcements.each_with_index do |announcement, index| %>
      <% if index != 0 %>
        <div class="row"><div class="col"><hr /></div></div>
      <% end %>

      <div class="row announcement" id="<%= dom_id(announcement) %>">
        <div class="col-sm-1 text-center">
          <%= link_to announcements_path(anchor: dom_id(announcement)) do %>
            <strong><%= announcement.published_at.strftime("%b %d") %></strong>
          <% end %>
        </div>
        <div class="col">
          <strong class="<%= announcement_class(announcement.announcement_type) %>"><%= announcement.announcement_type.titleize %>:</strong>
          <strong><%= announcement.name %></strong>
          <%= simple_format announcement.description %>
        </div>
      </div>
    <% end %>

    <% if @announcements.empty? %>
      <div>Exciting stuff coming very soon!</div>
    <% end %>
  </div>
</div>

app/views/announcements/show.html.erb
<h1> <%= @announcements.name %> </h1>
<h5> <%=  @announcements.description %></h5>