config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  draw :madmin
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
authenticate :user, lambda { |u| u.admin? } do
  mount Sidekiq::Web => '/sidekiq'

  namespace :madmin do
    resources :impersonates do
      post :impersonate, on: :member
      post :stop_impersonating, on: :collection
    end
  end
end

  # resources :notifications, only: [:index]
  # resources :announcements, only: [:index]
  resources :posts, except: [:new]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  devise_scope :user do
    get '/users/:id/profile' => 'users#profile', :as => 'user_profile'
  end
  devise_scope :announcements do
    get '/announcements/:id' => 'announcements#show', :as => 'announcements_post'
  end
  root to: 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/announcement.rb
class Announcement < ApplicationRecord
  TYPES = %w{ new fix update }

  after_initialize :set_defaults

  validates :announcement_type, :description, :name, :published_at, presence: true
  validates :announcement_type, inclusion: { in: TYPES }

  def set_defaults
    self.published_at      ||= Time.zone.now
    self.announcement_type ||= TYPES.first
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" and "follower" interface
  belongs_to :followable, polymorphic: true
  belongs_to :follower,   polymorphic: true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/post.rb
class Post < ApplicationRecord
  has_rich_text :post
  belongs_to :user
end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :user

  Devise.omniauth_configs.keys.each do |provider|
    scope provider, ->{ where(provider: provider) }
  end

  def client
    send("#{provider}_client")
  end

  def expired?
    expires_at? && expires_at <= Time.zone.now
  end

  def access_token
    send("#{provider}_refresh_token!", super) if expired?
    super
  end


  def twitter_client
    Twitter::REST::Client.new do |config|
      config.consumer_key        = Rails.application.secrets.twitter_app_id
      config.consumer_secret     = Rails.application.secrets.twitter_app_secret
      config.access_token        = access_token
      config.access_token_secret = access_token_secret
    end
  end

  def twitter_refresh_token!(token); end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable, :omniauthable

  has_one_attached :avatar
  has_one_attached :banner
  has_person_name

  extend FriendlyId
  friendly_id :id, use: :slugged

  has_many :notifications, as: :recipient
  has_many :services
  has_many :posts
  acts_as_followable
  acts_as_follower
end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
  before_action :mark_as_read, if: :user_signed_in?

  def index
    @announcements = Announcement.order(published_at: :desc)
  end

  def show
    @announcements = Announcement.find(params[:id])
  end

  private

    def mark_as_read
      current_user.update(announcements_last_read_at: Time.zone.now)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  impersonates :user
  include Pundit

  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :username])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :avatar, :banner, :username])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @post = Post.new
    @myPost = Announcement.order(created_at: :desc)
    @myPost += current_user.posts.order(created_at: :desc)
  end

  def terms
  end

  def privacy
  end
end

app/controllers/madmin/services_controller.rb
module Madmin
  class ServicesController < Madmin::ResourceController
  end
end

app/controllers/madmin/users_controller.rb
module Madmin
  class UsersController < Madmin::ResourceController
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :authenticate_user!

  def index
    # Convert the database records to Noticed notification instances so we can use helper methods
    #@notifications = current_user.notifications.map(&:to_notification)
    @notifications = nil
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    redirect_to root_path
  end

  def show
    @post = Post.find(params[:id])
    @author = User.find(@post.user_id)
  end

  def create
    @post = current_user.posts.create(post_param)
    Pusher.trigger('posts-channel','new-post', {
      user_id: current_user.id,
      username: current_user.username,
      caption: @post.post.body
    })
    redirect_to root_path, notice: "Message Posted"
  end

  private
  def post_param
    params.require(:post).permit(:post)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:profile]

  def profile
  end

  private
  def set_user
    @user = User.friendly.find(params[:id])
  end
end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
  def unread_announcements(user)
    last_announcement = Announcement.order(published_at: :desc).first
    return if last_announcement.nil?

    # Highlight announcements for anyone not logged in, cuz tempting
    if user.nil? || user.announcements_last_read_at.nil? || user.announcements_last_read_at < last_announcement.published_at
      "unread-announcements"
    end
  end

  def announcement_class(type)
    {
      "new" => "text-success",
      "update" => "text-warning",
      "fix" => "text-danger",
    }.fetch(type, "text-success")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/avatar_helper.rb
module AvatarHelper
  def avatar_path(object, options = {})
    size = options[:size] || 180
    default_image = options[:default] || "mp"
    base_url =  "https://secure.gravatar.com/avatar"
    base_url_params = "?s=#{size}&d=#{default_image}"

    if object.respond_to?(:avatar) && object.avatar.attached? && object.avatar.variable?
      object.avatar.variant(resize_to_fill: [size, size, { gravity: 'Center' }])
    elsif object.respond_to?(:email) && object.email
      gravatar_id = Digest::MD5::hexdigest(object.email.downcase)
      "#{base_url}/#{gravatar_id}#{base_url_params}"
    else
      "#{base_url}/00000000000000000000000000000000#{base_url_params}"
    end
  end
end

app/helpers/banner_helper.rb
module BannerHelper
  def banner_path(object)
    if object.respond_to?(:banner) && object.banner.attached? && object.banner.variable?
      object.banner.variant(resize_to_fill: [970, 250])
    else
      image_url("default-banner.png")
    end
  end
end

app/helpers/bootstrap_helper.rb
module BootstrapHelper
  def bootstrap_class_for(flash_type)
    {
      success: "alert-success",
      error: "alert-danger",
      alert: "alert-warning",
      notice: "alert-success"
    }.stringify_keys[flash_type.to_s] || flash_type.to_s
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="post-write">
  <%= form_for @post do |f| %>
    <div class="field">
      <%= f.label :post %>
      <%= f.rich_text_area :post %>
    </div>
    <div class="form-group">
      <button type="submit" class="btn btn-primary">Send</button>
    </div>
  <% end %>
</div>
<br>
<div class="feed" id="feed_section">
  <% @myPost.each do |p| %>
    <% if p.instance_of? Post %>
      <a href="<%= post_path(p.id) %>">
      <div class="post">
        <div class="post-pp">
          <a href="<%= user_profile_path(p.user_id) %>">
            <%= image_tag avatar_path(current_user, size: 40), class: "feed-pp" %>
          </a>
        </div>
        <div class="post-content">
          <a href="<%= user_profile_path(p.user_id) %>">
            <%= current_user.username %>
          </a>
          <span>·</span>
          <a href="<%= post_path(p.id) %>">
            <time datetime="<%= p.created_at %>">
              <%=
                if Time.now.day - p.created_at.day > 0
                  (Time.now.day - p.created_at.day > 3) ? p.created_at.strftime("%d %B") : (Time.now.day - p.created_at.day).to_s << 'd'
                elsif Time.now.hour - p.created_at.hour > 0
                  (Time.now.hour - p.created_at.hour).to_s << 'h'
                elsif Time.now.min - p.created_at.min > 0
                  (Time.now.min - p.created_at.min).to_s << 'm'
                else
                  (Time.now.sec - p.created_at.sec).to_s << 's'
                end %>
            </time>
          </a>
          <span>
            <%= p.post.body %>
          </span>
        </div>
      </div>
      </a>
    <% elsif p.instance_of? Announcement%>
      <div class="announcement">
        <a href="<%= announcements_post_path(p.id) %>">
          <h1> <%= p.name %> </h1>
          <h5> <%=  p.description %></h5>
          <p>This is a Announcement !</p>
        </a>
      </div>
    <% end %>
    <br />
  <% end %>
</div>
<script>
    var channel = pusher.subscribe('posts-channel');
    channel.bind('new-post', function(data)  {
        console.log(data);
        // let post = data.caption;
        // let author = data.username;
        // let div = document.getElementById('feed_section');
        // let new_content = document.createElement("div");
        // new_content.className = "post";
        // new_content.innerHTML = "<p> Post from " + author + " : " + post + "<br />";
        // div.insertBefore(new_content, div.firstChild);
    });
</script>

app/views/home/privacy.html.erb
<h1>Privacy Policy</h1>
<p class="lead">Lorem Ipsum.</p>
<p>
  Lorem ipsum dolor sit amet. In nulla soluta ut nesciunt consequatur id vero dolore. Non consequuntur dolorem quo autem commodi non rerum sint ab molestiae rerum eum consequatur quisquam est voluptas fugiat. Cum incidunt velit At corporis velit et architecto rerum id quidem numquam 33 quasi maxime. Id ducimus neque eos quisquam iure et eveniet temporibus ab nisi asperiores et sint beatae est nulla deserunt.

  Cum assumenda omnis in quae inventore sit vero autem. Qui enim maiores ad neque dolorem ut repellendus voluptatum. Aut reprehenderit unde eum autem ratione cum illum dignissimos ut omnis assumenda ut distinctio obcaecati a corrupti consequatur et assumenda rerum! Hic beatae veritatis eum veritatis voluptatem explicabo galisum qui earum dolores eum deserunt numquam quo ducimus temporibus.

  Qui perferendis aliquam rem reprehenderit excepturi ut suscipit quaerat? Qui consequatur voluptas non aliquam ducimus eos ipsa voluptate in libero omnis aut delectus autem nam galisum quod. Est officiis consequatur et voluptas obcaecati 33 voluptatem nulla aut nostrum optio eum voluptas illum aut cumque maiores est laudantium consequatur. Quo mollitia magni ea voluptate blanditiis in eius natus.
</p>

app/views/home/terms.html.erb
<h1>Terms of Service</h1>
<p class="lead">Lorem Ipsum.</p>
<p>
  Lorem ipsum dolor sit amet. In nulla soluta ut nesciunt consequatur id vero dolore. Non consequuntur dolorem quo autem commodi non rerum sint ab molestiae rerum eum consequatur quisquam est voluptas fugiat. Cum incidunt velit At corporis velit et architecto rerum id quidem numquam 33 quasi maxime. Id ducimus neque eos quisquam iure et eveniet temporibus ab nisi asperiores et sint beatae est nulla deserunt.

  Cum assumenda omnis in quae inventore sit vero autem. Qui enim maiores ad neque dolorem ut repellendus voluptatum. Aut reprehenderit unde eum autem ratione cum illum dignissimos ut omnis assumenda ut distinctio obcaecati a corrupti consequatur et assumenda rerum! Hic beatae veritatis eum veritatis voluptatem explicabo galisum qui earum dolores eum deserunt numquam quo ducimus temporibus.

  Qui perferendis aliquam rem reprehenderit excepturi ut suscipit quaerat? Qui consequatur voluptas non aliquam ducimus eos ipsa voluptate in libero omnis aut delectus autem nam galisum quod. Est officiis consequatur et voluptas obcaecati 33 voluptatem nulla aut nostrum optio eum voluptas illum aut cumque maiores est laudantium consequatur. Quo mollitia magni ea voluptate blanditiis in eius natus.
</p>

app/views/notifications/index.html.erb
<h1>Notifications</h1>

<ul>
  <%# @notifications.each do |notification| %>
    <%# Customize your notification format here. We typically recommend a `message` and `url` method on the Notification classes. %>
    <%#= link_to notification.message, notification.url %>

<!--    <li><%#= notification.params %></li>-->
  <%# end %>
  <p></p>
</ul>